[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "open-data-quality"
version = "0.1.1"
description = "A lightweight, configuration-driven data quality toolkit"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
license-files = ["LICENSE"]
authors = [{name = "Bruce-Xu-git"}]
keywords = ["data-quality", "data-governance", "data-validation", "csv"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: Information Technology",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Topic :: Software Development :: Quality Assurance"
]

[project.urls]
Homepage = "https://github.com/wefsdfasdfaef/open-data-quality"
Repository = "https://github.com/wefsdfasdfaef/open-data-quality"
Issues = "https://github.com/wefsdfasdfaef/open-data-quality/issues"
Changelog = "https://github.com/wefsdfasdfaef/open-data-quality/blob/main/CHANGELOG.md"

[project.scripts]
open-data-quality = "open_data_quality.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
