"""Human-readable reporting for Open Data Quality."""

from __future__ import annotations

from html import escape
from typing import Any


def render_html(report: dict[str, Any], title: str = "Open Data Quality Report") -> str:
    """Render a self-contained HTML report from a quality-check result."""
    rows = []
    for item in report.get("results", []):
        rule = item.get("rule", {})
        rule_type = escape(str(rule.get("type", "unknown")))
        column = escape(str(rule.get("column", "")))
        status = "PASS" if item.get("passed") else "FAIL"
        failed_count = int(item.get("failed_count", 0))
        failed_rows = ", ".join(str(value) for value in item.get("failed_rows", [])) or "—"
        rows.append(
            "<tr>"
            f"<td>{rule_type}</td><td>{column}</td><td>{status}</td>"
            f"<td>{failed_count}</td><td>{escape(failed_rows)}</td>"
            "</tr>"
        )

    score = float(report.get("score", 0))
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{escape(title)}</title>
<style>
body{{font-family:system-ui,-apple-system,sans-serif;max-width:1100px;margin:40px auto;padding:0 20px;color:#1f2937}}
h1{{margin-bottom:8px}}.summary{{display:grid;grid-template-columns:repeat(5,minmax(100px,1fr));gap:12px;margin:24px 0}}
.card{{border:1px solid #e5e7eb;border-radius:10px;padding:16px}}.value{{font-size:28px;font-weight:700}}
table{{width:100%;border-collapse:collapse}}th,td{{border-bottom:1px solid #e5e7eb;text-align:left;padding:10px}}th{{background:#f9fafb}}
small{{color:#6b7280}}@media(max-width:700px){{.summary{{grid-template-columns:1fr 1fr}}}}
</style>
</head>
<body>
<h1>{escape(title)}</h1>
<small>Generated by Open Data Quality</small>
<section class="summary">
<div class="card"><div class="value">{int(report.get('rows', 0))}</div><div>Rows</div></div>
<div class="card"><div class="value">{int(report.get('checks', 0))}</div><div>Checks</div></div>
<div class="card"><div class="value">{int(report.get('passed', 0))}</div><div>Passed</div></div>
<div class="card"><div class="value">{int(report.get('failed', 0))}</div><div>Failed</div></div>
<div class="card"><div class="value">{score:.2f}%</div><div>Score</div></div>
</section>
<table>
<thead><tr><th>Rule</th><th>Column</th><th>Status</th><th>Failed count</th><th>Sample row numbers</th></tr></thead>
<tbody>{''.join(rows)}</tbody>
</table>
</body>
</html>
"""
